#!/usr/bin/env bash
# print a list of currently running processes.
# show all processes, for all users, including those
# which might not have a TTY
# Print in a user-oriented format
# Show process hierarchy

ps -auxf
